### ISSUE TITLE
ログイン機能がバグってる気がします

### ISSUE THREAD

**Issue by Dython-layton** [itokaoru/software_presentation#1]
会員登録が上手くいきません...。

**Comment by Dython-layton** [comment]
僕の端末側が原因なのか分からないので確認のほどよろしくお願いいたします。

**Comment by TmpAccountForMLClass** [comment]
Issueの報告には[Issue Template](https://github.com/stevemao/github-issue-templates/blob/master/simple/ISSUE_TEMPLATE.md)を使って頂けると良いと思います。

[[GitHub - stevemao/github-issue-templates: A collection of GitHub issue and pull request templates](https://github.com/stevemao/github-issue-templates)](https://github.com/stevemao/github-issue-templates)には他のテンプレートもありますので各自わかりやすいものを使ってください。

**Comment by itokaoru** [comment]
ログイン機能を訂正しました．softproject内のsetting.pyを一部変更しました．ありがとうございます．

**Comment by Dython-layton** [comment]
お二方、ありがとうございます！！

**Comment by hara-lab** [comment]
## Expected Behavior
`python manage.py runserver 172.17.0.2:8000`によりアプリを立ち上げる。

## Actual Behavior
README.mdの指示に従いWindowsからアプリを立ち上げようと試みましたが、`このサイトにアクセスできません　172.17.0.2:8000からの応答時間が長すぎます`と表示され、アプリが立ち上がりません。

## Specifications

  - Version: 
  　- Windows OS： Windows 10 Home   22H2
  　- Ubuntu on Windows： Ubuntu 20.04 LTS
  　- Docker Desktop： 20.10.21

**Comment by quantum708** [comment]
私もWindowsですが、サイトは開くことができました。ログイン後の画面が表示されるか試してみます。

**Comment by TmpAccountForMLClass** [comment]
> ## Expected Behavior
> 
> 「python manage.py runserver 172.17.0.2:8000」によりアプリを立ち上げる。
> ## Actual Behavior
> 
> Windowsからアプリを立ち上げようと試みましたが、「このサイトにアクセスできません　172.17.0.2:8000からの応答時間が長すぎます」と表示され、アプリが立ち上がりません。
> ## Specifications
> 
>     * Version: Windows 10 Home   22H2

Issueは内容ごとに分けてください。Issues画面右上付近にあるNew Issueという緑色のボタンから新しいIssueのページが作れます。

**Comment by hara-lab** [comment]
ありがとうございます。お手数おかけして申し訳ないです。

**Comment by itokaoru** [comment]
再度ログイン, ログアウト機能を修正したため試してみてください.
