### ISSUE TITLE
Dockerを利用した状態でアプリが起動できない

### ISSUE THREAD

**Issue by hara-lab** [itokaoru/software_presentation#11]
https://github.com/itokaoru/software_presentation/issues/1#issuecomment-1371801091
(別のissueに間違えて投稿してしまったため改めてこちらでissueを立ち上げています)
(なお、こちらのissueですが一度消えてしまったので再度立ち上げています)

**Comment by itokaoru** [comment]
Ubuntu, Mac, Windows (一部)では動作確認ができています。
Windowsでは不具合が確認される場合もあるので, その場合は Docker を利用せずにローカル環境でアプリを起動
していただきたいと思います。
