### ISSUE TITLE
作成機能でのエラー2

### ISSUE THREAD

**Issue by quantum708** [itokaoru/software_presentation#13]
画像を選択しなくても作成するボタン押せたんですけど、その後にTOP押すとエラー画面出ました。

**Comment by quantum708** [comment]
(追記)画像を含めて作成すると問題なく動いたので、画像の参照がされてない場合は作成できないようにする方が良いかも？

**Comment by itokaoru** [comment]
画像選択なしでも店舗作成を可能にしました．
画像を設定せずとも作成できる方がユーザ側としては使いやすいと思われます．
また，作成後は index に戻るようにしました．
確認のほどお願いします．

**Comment by quantum708** [comment]
確認できました。
ありがとうございます。
