### ISSUE TITLE
TOP 画面のデザインについて

### ISSUE THREAD

**Issue by itokaoru** [itokaoru/software_presentation#15]
私がBootstrap にて枠組みを大まかに決めていましたが, 各店舗の囲いが少し大きすぎる気もします.
デザイン担当の方, 気になるようでしたら調整の程よろしくお願いします.
そこまで気にならない場合は返答のみで結構です.

**Comment by hara-lab** [comment]
TOP画面のデザインに関して、修正を行いました。
各店舗の囲いを少し小さくし、それに伴い右側のTOP2の店舗の囲いを大きくしています。
さらに、TOP2の枠組内のフォントサイズを大きくし、`＜＜前へ`や`次へ＞＞`の配置を調整しました。
### 調整前
![ramen_before](https://user-images.githubusercontent.com/72585366/212706148-0cf60d14-aaea-4b5b-b4f5-81c129c469b2.png)



### 調整後
![ramen_after](https://user-images.githubusercontent.com/72585366/212705826-9ce2d30d-3e50-4157-ac7a-f684f77a03e1.png)

![ramen_after2](https://user-images.githubusercontent.com/72585366/212707369-05cb799d-7643-41dd-bb9a-9e90c4fc7e84.png)

**Comment by hara-lab** [comment]
調整はこのような感じで良いでしょうか？
もしこれで良ければプルリクエストします。

**Comment by itokaoru** [comment]
ありがとうございます！プルリクエストお願いします！
