### ISSUE TITLE
会員登録ができない

### ISSUE THREAD

**Issue by quantum708** [itokaoru/software_presentation#4]
ユーザーIDとパスワードを入力しても
利用できないユーザーIDやパスワードの可能性があります. 入力内容を再度ご確認ください。
と表示されてアカウント作成できませんでした。
どんな文字列なら作成可能なのでしょうか？

**Comment by itokaoru** [comment]
ログイン, ログアウト機能を修正したためもう一度試してみてください.

**Comment by hara-lab** [comment]
元々は登録しようとしたIDとパスワードを入力した後、この画面が表示されるエラーが起きていました。
![ramen6](https://user-images.githubusercontent.com/72585366/212465794-78937e06-8ff7-41b9-836e-94366737c925.png)


しかし、新たに修正されたバージョンで同じことをしようとした際、上記のようなエラー画面は出ず、問題なく会員登録ができるようになったことを確認しました。

**Comment by itokaoru** [comment]
承知しました. 確認ありがとうございます！
