### ISSUE TITLE
画面の文字化け

### ISSUE THREAD

**Issue by Dython-layton** [itokaoru/software_presentation#5]
Expected Behavior
アプリの文字(日本語)が表示される。

Actual Behavior
Windowsではアプリは動作しなかったので、wslでgooglechromeを開いてアプリで起動しました。
その結果、文字化けを起こしており文字が読めませんでした。

Specifications
Version: Windows 10

**Comment by itokaoru** [comment]
Windows では不具合が確認される方もいるようです. (Windows で普通に動作する人もいる.)
その場合はローカルで回していただくという方向で行きましょう.
