### ISSUE TITLE
「編集する」ボタンを押したときのエラー

### ISSUE THREAD

**Issue by hara-lab** [itokaoru/software_presentation#6]
## Expected Behavior
「編集する」ボタンを押すことで各店舗のレビューを編集する。

## Actual Behavior
アプリを立ち上げ、各店舗のレビューを「編集する」ボタンから編集しようとすると、`403 Forbidden`というエラーが表示される。

![ramen1](https://user-images.githubusercontent.com/72585366/212459648-dfbae11b-0d02-4ed9-8f98-477e4781cba5.png)
![ramen2](https://user-images.githubusercontent.com/72585366/212459653-e07f1bff-0ba6-4165-b274-d050ee686f54.png)

**Comment by itokaoru** [comment]
ログイン, ログアウト機能を修正したのでもう一度試してみてください.

**Comment by hara-lab** [comment]
新たに更新されたバージョンで試してみましたが、改善されておらず引き続き`403 Forbidden`というエラーメッセージが表示されている状態です。
他の方はどうでしょうか？

**Comment by itokaoru** [comment]
改めて確認したところ, コンテンツ作成者にのみ権限を付与しています.
そのため「べらしお」を作成した本人である私にのみ編集および削除権限があります.

(なお, 現在は削除機能は排除しています. )

**Comment by itokaoru** [comment]
ローカルで変更する場合はcreatesuperuser等で管理者権限を作成後,
admin権限から変更してみてください.

python manage.py createsuperuser
で管理者権限の作成
http://---------/admin/
にて管理画面に遷移することができます.

**Comment by hara-lab** [comment]
ありがとうございます。どうやら解決したようです。


git bashのコマンドで`winpty python manage.py createsuperuser`を打ち、新たに管理者画面にアクセスできるユーザーIDとパスワードを作成しました（`nakamozu`というユーザー名にしています）。
そして管理者画面の`Books`内の店舗（下図では「麺や 鳥の鶏次」）の`User`を新たに`nakamozu`とし保存しました。

![ramen8](https://user-images.githubusercontent.com/72585366/212479902-6c58e2ac-7e0e-43b4-953f-2ed0ec6543f0.png)

さらにその後、アプリから設定を変えた店舗の「編集する」ボタンを押すと下図のような画面に遷移することが確認できました。

![ramen9](https://user-images.githubusercontent.com/72585366/212480047-e4480225-90c2-4c40-b08b-4111e71506d6.png)

**Comment by itokaoru** [comment]
解決したようでなによりです. 確認ありがとうございます.
