### ISSUE TITLE
コード改変を行う際のプルリクエストまでの一連の操作

### ISSUE THREAD

**Issue by hara-lab** [itokaoru/software_presentation#8]
1. 伊藤さんのgithubリポジトリより、`Fork`ボタンからフォークを行い自身のリモートリポジトリを作成する。

2. フォークした後のリモートリポジトリから自身のローカルPCに`git clone`する。

3. 自身のローカルPCで新たにブランチを切るなどして、コードの改変を行う。

4. 変更後のファイルを`git add`する。

- なお`git add`を行う際、`git status`コマンドを打つと`Untracked files：`に変更していないファイル一覧も表示されるので、`modified:`と表示されているファイル名だけを指定して`git add`する必要がある。
![ramen3](https://user-images.githubusercontent.com/72585366/212462944-98a40c7f-7d55-4736-89b3-2d847744d8f4.png)

5. `git commit`し、`git push`コマンドでリモートリポジトリにプッシュする。（下図ではpractice2のブランチをプッシュしている。）
![ramen5](https://user-images.githubusercontent.com/72585366/212463088-cfa9e00d-f1f2-4239-bef0-15b682b1f5d6.png)

6. 最後に伊藤さんのフォーク元のリポジトリにプルリクエストを送る。

**Comment by itokaoru** [comment]
ありがとうございます. 変更点, 改善点あれば皆さんpull request を送ってください.
