### ISSUE TITLE
作成機能でのエラー

### ISSUE THREAD

**Issue by nakagawa22116** [itokaoru/software_presentation#9]
作成ボタンから新しくラーメン屋を追加しようとするとエラーが発生する。

**Comment by itokaoru** [comment]
作成機能に関しては問題なく動作するはずです. ログイン後もう一度お試しください.

**Comment by itokaoru** [comment]
現在，画像設定なしで作成が可能となっています．
改めて確認お願いします．

**Comment by itokaoru** [comment]
こちらで確認したため閉じておきます．
